# Generated by Django 5.2.5 on 2026-08-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrosswalkForm",
            fields=[
                (
                    "canonical_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("jurisdiction", models.CharField(blank=True, max_length=100)),
                ("form_id", models.CharField(blank=True, max_length=200)),
                ("canonical_name", models.CharField(max_length=500)),
                ("department", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("is_efileable", models.BooleanField(default=False)),
                ("is_form", models.BooleanField(default=True)),
                ("source_urls", models.JSONField(default=list)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "registry_index",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
            ],
            options={
                "verbose_name": "Crosswalk form",
                "verbose_name_plural": "Crosswalk forms",
                "ordering": ["registry_index"],
            },
        ),
        migrations.CreateModel(
            name="CrosswalkMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mapping_index", models.PositiveIntegerField()),
                ("category", models.CharField(blank=True, max_length=300)),
                ("case_type", models.CharField(blank=True, max_length=300)),
                ("filing_type", models.CharField(blank=True, max_length=500)),
                ("filing_phase", models.CharField(blank=True, max_length=100)),
                ("court_names", models.JSONField(default=list)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("association_status", models.CharField(blank=True, max_length=100)),
                ("catalog_status", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="crosswalk_review.crosswalkform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crosswalk mapping",
                "verbose_name_plural": "Crosswalk mappings",
                "ordering": ["form", "mapping_index"],
                "unique_together": {("form", "mapping_index")},
            },
        ),
        migrations.CreateModel(
            name="MappingVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("correct", "✓ Correct"),
                            ("incorrect", "✗ Incorrect"),
                            ("unsure", "? Unsure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verdicts",
                        to="crosswalk_review.crosswalkmapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapping verdict",
                "verbose_name_plural": "Mapping verdicts",
                "ordering": ["-updated_at"],
                "unique_together": {("mapping", "reviewer_name")},
            },
        ),
    ]
