# Generated by Django 5.2.5 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crosswalk_review", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                ("reviewed_title", models.CharField(blank=True, max_length=500)),
                (
                    "title_verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correct", "✓ Correct"),
                            ("incorrect", "✗ Incorrect"),
                            ("unsure", "? Unsure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reviewed_form_id", models.CharField(blank=True, max_length=200)),
                (
                    "form_id_verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("correct", "✓ Correct"),
                            ("incorrect", "✗ Incorrect"),
                            ("unsure", "? Unsure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="reviews",
                        to="crosswalk_review.crosswalkform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form review",
                "verbose_name_plural": "Form reviews",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="mappingverdict",
            name="field_verdicts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="mappingverdict",
            name="lookup_context",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="mappingverdict",
            name="reviewed_category",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="mappingverdict",
            name="reviewed_case_type",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="mappingverdict",
            name="reviewed_filing_type",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="mappingverdict",
            name="verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct", "✓ Correct"),
                    ("incorrect", "✗ Incorrect"),
                    ("unsure", "? Unsure"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="formreview",
            constraint=models.UniqueConstraint(
                fields=("form", "reviewer_name"),
                name="unique_form_review_reviewer",
            ),
        ),
    ]
