"""Generated by ``manage.py extract_config_text``. Do not edit by hand.

Every user-facing string configured in a state's YAML file, restated as a
``pgettext_lazy`` call so ``makemessages`` can find it. The message context is
the UI text key, matching how ``efile.utils.ui_text`` looks the string up at
request time. Nothing imports this module.
"""

from django.utils.translation import pgettext_lazy

CONFIG_STRINGS = [
    # illinois.yaml
    # Translators: The partner paragraph on this jurisdiction's About page. Partners approve their own wording, so set it per state.
    pgettext_lazy(
        "about.project_partner_description",
        "LITEFile's Illinois e-filing integration was developed in close partnership with Illinois Legal Aid Online (ILAO), who provided project leadership, co-development, and funding to expand accessible electronic court filing for self-represented litigants in Illinois.",
    ),
    # vermont.yaml
    # Translators: The partner paragraph on this jurisdiction's About page. Partners approve their own wording, so set it per state.
    pgettext_lazy(
        "about.project_partner_description",
        "LITEFile's Vermont e-filing integration was developed in close partnership with Legal Services Vermont (LSV), who collaborated on funding, building, and deploying LITEFile to expand accessible electronic court filing for self-represented litigants in Vermont.",
    ),
    # Translators: What courts here usually call the document that opens a case, used as an example when asking the filer which PDF is the main one. Vermont says complaint.
    pgettext_lazy(
        "terms.starting_document_example",
        "complaint",
    ),
]
