#!/usr/bin/env python3
"""Freeze classification run inputs and write consistent notebook summaries."""

import csv
import hashlib
import json
import shutil
import subprocess
from pathlib import Path

PROMPTFOO_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = PROMPTFOO_ROOT.parents[1]
RUNS_ROOT = PROMPTFOO_ROOT / "lab-notebook" / "runs"

RUNS = {
    "2026-08-22-classification-stratified-v1-baseline": {
        "config": "promptfooconfig.classification-baseline.yaml",
        "purpose": "Initial two-stage baseline.",
        "validity": "diagnostic_only",
        "note": "The evaluated parent context leaked the target value at the level being classified.",
    },
    "2026-08-22-classification-stratified-v2-role-rubric": {
        "config": "promptfooconfig.classification-role-rubric.yaml",
        "purpose": "Initial role-rubric variation.",
        "validity": "diagnostic_only",
        "note": "The evaluated parent context leaked the target value at the level being classified.",
    },
    "2026-08-22-classification-stratified-v2-form-crosswalk": {
        "config": "promptfooconfig.classification-form-crosswalk.yaml",
        "purpose": "Initial exact-form crosswalk variation.",
        "validity": "diagnostic_only",
        "note": "The evaluated parent context leaked the target value at the level being classified.",
    },
    "2026-08-22-classification-stratified-v3-retrieval-shortlist": {
        "config": "promptfooconfig.classification-retrieval-shortlist.yaml",
        "purpose": "Initial Python-shortlist variation.",
        "validity": "diagnostic_only",
        "note": "The evaluated parent context leaked the target value at the level being classified.",
    },
    "2026-08-22-classification-stratified-v1-baseline-hierarchy-corrected": {
        "config": "promptfooconfig.classification-baseline.yaml",
        "purpose": "Valid two-stage evidence-plus-source baseline.",
        "validity": "valid",
        "note": "Baseline for the corrected stratified matrix.",
    },
    "2026-08-22-classification-stratified-v2-role-rubric-hierarchy-corrected": {
        "config": "promptfooconfig.classification-role-rubric.yaml",
        "purpose": "Two-stage variation with explicit category/type/filing distinctions.",
        "validity": "valid",
        "note": "Improved overall accuracy, but hurt one Vermont case-type decision.",
    },
    "2026-08-22-classification-stratified-v2-form-crosswalk-hierarchy-corrected": {
        "config": "promptfooconfig.classification-form-crosswalk.yaml",
        "purpose": "Three-stage variation with deterministic exact-form retrieval.",
        "validity": "valid",
        "note": "Best ordinary code/name response run; crosswalk suggestions remained explicitly unverified.",
    },
    "2026-08-22-classification-stratified-v3-retrieval-shortlist-hierarchy-corrected": {
        "config": "promptfooconfig.classification-retrieval-shortlist.yaml",
        "purpose": "Three-stage variation with a Python top-12 candidate shortlist.",
        "validity": "valid",
        "note": "Reduced prompt tokens but also removed useful contrast candidates.",
    },
    "2026-08-22-classification-stratified-v3-guarded-form-crosswalk": {
        "config": "promptfooconfig.classification-guarded-form-crosswalk.yaml",
        "purpose": "Crosswalk variation with qualifier and exact-copy instructions.",
        "validity": "valid",
        "note": "Extra copying instructions did not prevent canonical-name rewriting.",
    },
    "2026-08-22-classification-stratified-v4-reference-form-crosswalk": {
        "config": "promptfooconfig.classification-reference-form-crosswalk.yaml",
        "purpose": "Crosswalk variation where Python resolves a short candidate reference.",
        "validity": "valid",
        "note": "Best run; exact taxonomy strings and current route keys never had to be generated by the model.",
    },
}

INPUTS = [
    "data/classification_taxonomy_snapshot.json",
    "data/tyler_label_reviews.json",
    "scripts/build_classification_sentinel.py",
    "prompts/taxonomy_classification_study.py",
    "assertions/taxonomy_classification.js",
]

EXTERNAL_INPUTS = {
    "efile_taxonomy_classification.yaml": (
        REPOSITORY_ROOT
        / "efile_app"
        / "efile"
        / "prompts"
        / "efile_taxonomy_classification.yaml"
    ),
}


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def evaluated_cases(document):
    cases = {}
    for result in document["results"]["results"]:
        index = result["testIdx"]
        cases.setdefault(
            index,
            {
                "description": result.get("testCase", {}).get("description", ""),
                "vars": result["vars"],
                "metadata": result["metadata"],
            },
        )
    return [cases[index] for index in sorted(cases)]


def failure_rows(document):
    rows = []
    for result in document["results"]["results"]:
        if result.get("success"):
            continue
        output = str((result.get("response") or {}).get("output", "")).replace(
            "\n", " "
        )
        rows.append(
            {
                "provider": result["provider"].get("label", result["provider"]["id"]),
                "case_id": result["metadata"].get("case_id", ""),
                "level": result["metadata"].get("classification_level", ""),
                "score": result.get("score", 0),
                "output_excerpt": output[:400],
            }
        )
    return rows


def write_manifest(run_dir, meta, document, digests):
    stats = document["results"]["stats"]
    revision = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=PROMPTFOO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    package_lock = json.loads(
        (PROMPTFOO_ROOT / "package-lock.json").read_text(encoding="utf-8")
    )
    promptfoo_version = package_lock["packages"]["node_modules/promptfoo"]["version"]
    lines = [
        "schema_version: 1",
        f"run_id: {run_dir.name}",
        f"validity: {meta['validity']}",
        f"eval_id: {document.get('evalId', '')}",
        f"git_revision: {revision}",
        f"promptfoo_version: {promptfoo_version}",
        f"config: {meta['config']}",
        "models:",
        "  - gpt-5.4-nano",
        "  - mistral-large-3",
        "results:",
        f"  runs: {len(document['results']['results'])}",
        f"  passes: {stats['successes']}",
        f"  failures: {stats['failures']}",
        f"  errors: {stats['errors']}",
        "input_sha256:",
    ]
    lines.extend(f"  {name}: {digest}" for name, digest in sorted(digests.items()))
    (run_dir / "manifest.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_readme(run_dir, meta, document, failures):
    stats = document["results"]["stats"]
    total = len(document["results"]["results"])
    rate = 100 * stats["successes"] / total
    token_usage = stats.get("tokenUsage", {})
    validity = (
        "This run is valid for the corrected comparison."
        if meta["validity"] == "valid"
        else "This run is diagnostic only and is excluded from the final comparison."
    )
    failure_table = "No scored failures."
    if failures:
        lines = ["| Model | Case | Level | Score |", "| --- | --- | --- | ---: |"]
        lines.extend(
            f"| {row['provider']} | {row['case_id']} | {row['level']} | {row['score']} |"
            for row in failures
        )
        failure_table = "\n".join(lines)
    content = f"""# {meta['purpose'].rstrip('.')}

## Result

{stats['successes']}/{total} selections passed ({rate:.2f}%), with {stats['errors']} API errors.
The run used {token_usage.get('total', 0):,} total tokens.

{validity} {meta['note']}

## Failures

{failure_table}

## Reproduction record

The `inputs/` directory contains the exact cases reconstructed from the raw Promptfoo result,
the evaluated config, renderer, scorer, live-catalog snapshot, reviewed labels, and builder.
`artifacts/result.json` is the raw Promptfoo output; stable aggregate tables are under `tables/`.
Numeric Tyler values in the snapshot are dated route-key observations, not gold identities.
The assertion scores the exact durable name and checks the returned route key or run-local
selection reference against the offered candidate.
"""
    (run_dir / "README.md").write_text(content, encoding="utf-8")


def main():
    comparison = []
    for run_id, meta in RUNS.items():
        run_dir = RUNS_ROOT / run_id
        result_path = run_dir / "artifacts" / "result.json"
        if not result_path.exists():
            continue
        document = json.loads(result_path.read_text(encoding="utf-8"))
        input_dir = run_dir / "inputs"
        input_dir.mkdir(exist_ok=True)
        cases_path = input_dir / "evaluated_cases.jsonl"
        cases_path.write_text(
            "".join(
                json.dumps(case, ensure_ascii=False, separators=(",", ":")) + "\n"
                for case in evaluated_cases(document)
            ),
            encoding="utf-8",
        )
        sources = [meta["config"], *INPUTS]
        digests = {"evaluated_cases.jsonl": sha256(cases_path)}
        for relative in sources:
            source = PROMPTFOO_ROOT / relative
            destination = input_dir / source.name
            shutil.copyfile(source, destination)
            digests[source.name] = sha256(destination)
        for name, source in EXTERNAL_INPUTS.items():
            destination = input_dir / name
            shutil.copyfile(source, destination)
            digests[name] = sha256(destination)
        failures = failure_rows(document)
        failures_path = run_dir / "tables" / "failures.csv"
        failures_path.parent.mkdir(exist_ok=True)
        if failures:
            with failures_path.open("w", encoding="utf-8", newline="") as stream:
                writer = csv.DictWriter(stream, fieldnames=list(failures[0]))
                writer.writeheader()
                writer.writerows(failures)
        write_manifest(run_dir, meta, document, digests)
        write_readme(run_dir, meta, document, failures)
        stats = document["results"]["stats"]
        prompt_tokens = sum(
            int((result.get("tokenUsage") or {}).get("prompt", 0))
            for result in document["results"]["results"]
        )
        comparison.append(
            {
                "run_id": run_id,
                "validity": meta["validity"],
                "passes": stats["successes"],
                "total": len(document["results"]["results"]),
                "accuracy": round(
                    stats["successes"] / len(document["results"]["results"]), 6
                ),
                "prompt_tokens": prompt_tokens,
                "errors": stats["errors"],
            }
        )
    study_dir = (
        PROMPTFOO_ROOT
        / "lab-notebook"
        / "studies"
        / "2026-08-22-stratified-classification"
    )
    study_dir.mkdir(parents=True, exist_ok=True)
    with (study_dir / "run-comparison.csv").open(
        "w", encoding="utf-8", newline=""
    ) as stream:
        writer = csv.DictWriter(stream, fieldnames=list(comparison[0]))
        writer.writeheader()
        writer.writerows(comparison)
    print(f"Recorded {len(comparison)} independent runs")


if __name__ == "__main__":
    main()
