# Generated by Django 5.2.5 on 2025-09-16 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('street_address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('county', models.CharField(choices=[('adams', 'Adams'), ('alexander', 'Alexander'), ('bond', 'Bond'), ('boone', 'Boone'), ('brown', 'Brown'), ('bureau', 'Bureau'), ('calhoun', 'Calhoun'), ('carroll', 'Carroll'), ('cass', 'Cass'), ('champaign', 'Champaign'), ('christian', 'Christian'), ('clark', 'Clark'), ('clay', 'Clay'), ('clinton', 'Clinton'), ('coles', 'Coles'), ('cook', 'Cook'), ('crawford', 'Crawford'), ('cumberland', 'Cumberland'), ('dekalb', 'DeKalb'), ('dewitt', 'DeWitt'), ('douglas', 'Douglas'), ('dupage', 'DuPage'), ('edgar', 'Edgar'), ('edwards', 'Edwards'), ('effingham', 'Effingham'), ('fayette', 'Fayette'), ('ford', 'Ford'), ('franklin', 'Franklin'), ('fulton', 'Fulton'), ('gallatin', 'Gallatin'), ('greene', 'Greene'), ('grundy', 'Grundy'), ('hamilton', 'Hamilton'), ('hancock', 'Hancock'), ('hardin', 'Hardin'), ('henderson', 'Henderson'), ('henry', 'Henry'), ('iroquois', 'Iroquois'), ('jackson', 'Jackson'), ('jasper', 'Jasper'), ('jefferson', 'Jefferson'), ('jersey', 'Jersey'), ('jodaviess', 'Jo Daviess'), ('johnson', 'Johnson'), ('kane', 'Kane'), ('kankakee', 'Kankakee'), ('kendall', 'Kendall'), ('knox', 'Knox'), ('lake', 'Lake'), ('lasalle', 'LaSalle'), ('lawrence', 'Lawrence'), ('lee', 'Lee'), ('livingston', 'Livingston'), ('logan', 'Logan'), ('macon', 'Macon'), ('macoupin', 'Macoupin'), ('madison', 'Madison'), ('marion', 'Marion'), ('marshall', 'Marshall'), ('mason', 'Mason'), ('massac', 'Massac'), ('mcdonough', 'McDonough'), ('mchenry', 'McHenry'), ('mclean', 'McLean'), ('menard', 'Menard'), ('mercer', 'Mercer'), ('monroe', 'Monroe'), ('montgomery', 'Montgomery'), ('morgan', 'Morgan'), ('moultrie', 'Moultrie'), ('ogle', 'Ogle'), ('peoria', 'Peoria'), ('perry', 'Perry'), ('piatt', 'Piatt'), ('pike', 'Pike'), ('pope', 'Pope'), ('pulaski', 'Pulaski'), ('putnam', 'Putnam'), ('randolph', 'Randolph'), ('richland', 'Richland'), ('rock_island', 'Rock Island'), ('saline', 'Saline'), ('sangamon', 'Sangamon'), ('schuyler', 'Schuyler'), ('scott', 'Scott'), ('shelby', 'Shelby'), ('stark', 'Stark'), ('stephenson', 'Stephenson'), ('tazewell', 'Tazewell'), ('union', 'Union'), ('vermilion', 'Vermilion'), ('wabash', 'Wabash'), ('warren', 'Warren'), ('washington', 'Washington'), ('wayne', 'Wayne'), ('white', 'White'), ('whiteside', 'Whiteside'), ('will', 'Will'), ('williamson', 'Williamson'), ('winnebago', 'Winnebago'), ('woodford', 'Woodford')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email_updates', models.BooleanField(default=False)),
                ('text_updates', models.BooleanField(default=False)),
                ('suffolk_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tyler_token', models.TextField(blank=True, null=True)),
                ('preferred_county', models.CharField(default='cook', max_length=50)),
                ('suffolk_access_token', models.TextField(blank=True, null=True)),
                ('suffolk_refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('firm_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
