# Generated by Django 5.2.5 on 2025-09-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default='IL', max_length=2),
        ),
    ]
