# Generated by Django 5.2.5 on 2026-06-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("efile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilingDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("jurisdiction", models.CharField(db_index=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitting", "Submitting"),
                            ("submitted", "Submitted"),
                            ("error", "Error"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("options", "Options"),
                            ("upload_first", "Upload lead document"),
                            ("case_information", "Case information"),
                            ("documents", "Documents"),
                            ("payment", "Payment"),
                            ("review", "Review"),
                            ("confirmation", "Confirmation"),
                        ],
                        default="options",
                        max_length=64,
                    ),
                ),
                ("existing_case", models.CharField(blank=True, max_length=20)),
                ("court_code", models.CharField(blank=True, max_length=100)),
                ("court_name", models.CharField(blank=True, max_length=255)),
                ("case_category_code", models.CharField(blank=True, max_length=100)),
                ("case_category_name", models.CharField(blank=True, max_length=255)),
                ("case_type_code", models.CharField(blank=True, max_length=100)),
                ("case_type_name", models.CharField(blank=True, max_length=255)),
                ("case_subtype_code", models.CharField(blank=True, max_length=100)),
                ("case_subtype_name", models.CharField(blank=True, max_length=255)),
                ("filing_type_code", models.CharField(blank=True, max_length=100)),
                ("filing_type_name", models.CharField(blank=True, max_length=255)),
                ("document_type_code", models.CharField(blank=True, max_length=100)),
                ("document_type_name", models.CharField(blank=True, max_length=255)),
                ("previous_case_id", models.CharField(blank=True, max_length=255)),
                ("docket_number", models.CharField(blank=True, max_length=255)),
                ("selected_payment_account_id", models.CharField(blank=True, max_length=255)),
                ("selected_payment_account_name", models.CharField(blank=True, max_length=255)),
                ("name_change_reason", models.TextField(blank=True)),
                ("optional_services", models.JSONField(blank=True, default=list)),
                ("extracted_guesses", models.JSONField(blank=True, default=dict)),
                ("submission_response", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="draft_user_status_idx"),
                    models.Index(fields=["jurisdiction", "status"], name="draft_jurisdiction_status_idx"),
                    models.Index(fields=["status", "updated_at"], name="draft_status_updated_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FilingDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Lead document"), ("supporting", "Supporting document")],
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("s3_key", models.CharField(blank=True, max_length=1024)),
                ("public_url", models.URLField(blank=True, max_length=2048)),
                ("filing_type_code", models.CharField(blank=True, max_length=100)),
                ("filing_type_name", models.CharField(blank=True, max_length=255)),
                ("document_type_code", models.CharField(blank=True, max_length=100)),
                ("document_type_name", models.CharField(blank=True, max_length=255)),
                ("filing_component_code", models.CharField(blank=True, max_length=100)),
                ("filing_component_name", models.CharField(blank=True, max_length=255)),
                ("courtesy_copy_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="efile.filingdraft",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FilingParty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("party_type", models.CharField(blank=True, max_length=100)),
                ("external_party_id", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=50)),
                ("organization_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, default="US", max_length=2)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties",
                        to="efile.filingdraft",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Filing parties",
                "ordering": ["role", "sort_order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="filingdocument",
            constraint=models.UniqueConstraint(
                fields=("draft", "role", "sort_order"),
                name="unique_document_order_per_draft_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="filingparty",
            constraint=models.UniqueConstraint(
                fields=("draft", "role", "sort_order"),
                name="unique_party_order_per_draft_role",
            ),
        ),
    ]
