# Generated by Django 5.2.5 on 2026-08-11 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0006_filingdocument_requested_optional_services'),
        ('efile', '0007_complete_workflow_migration'),
    ]

    operations = [
    ]
