# Generated by Django 5.2.5 on 2026-08-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0007_amount_in_controversy'),
        ('efile', '0009_filingdraft_payment_type_and_quoted_fees'),
    ]

    operations = [
    ]
