# Generated by Django 5.2.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("efile", "0011_merge_jurisdiction_accounts_and_workflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("jurisdiction", models.CharField(db_index=True, max_length=40)),
                ("court_code", models.CharField(blank=True, max_length=100)),
                ("court_name", models.CharField(blank=True, max_length=255)),
                ("case_category_name", models.CharField(blank=True, max_length=255)),
                ("case_type_name", models.CharField(blank=True, max_length=255)),
                ("lead_filing_type_name", models.CharField(blank=True, max_length=255)),
                ("filer_role", models.CharField(blank=True, max_length=60)),
                ("case_tracking_id", models.CharField(blank=True, max_length=255)),
                ("docket_number", models.CharField(blank=True, max_length=255)),
                ("case_title", models.CharField(blank=True, max_length=500)),
                ("checklist", models.JSONField(blank=True, default=dict)),
                ("guidance", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="filingdraft",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filing_drafts",
                to="efile.filingplan",
            ),
        ),
        migrations.AddField(
            model_name="filingdraft",
            name="filer_role",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="filingdocument",
            name="checklist_item_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="filingplan",
            index=models.Index(
                fields=["user", "jurisdiction"], name="plan_user_jurisdiction_idx"
            ),
        ),
    ]
