# Generated by Django 5.2.5 on 2026-08-18 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0012_filing_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(db_index=True, max_length=40)),
                ('case_tracking_id', models.CharField(max_length=255)),
                ('docket_number', models.CharField(blank=True, max_length=255)),
                ('case_title', models.CharField(blank=True, max_length=500)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-archived_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'jurisdiction', 'case_tracking_id'), name='unique_archived_case_per_user')],
            },
        ),
    ]
