# Generated by Django 5.2.5 on 2026-08-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0015_document_extraction_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingparty',
            name='party_role_hint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='filingparty',
            name='party_side',
            field=models.CharField(blank=True, choices=[('initiating', 'Plaintiff or petitioner'), ('responding', 'Defendant or respondent'), ('other', 'Someone else named in the case')], max_length=20),
        ),
    ]
