# Generated by Django 5.2.5 on 2026-08-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0016_party_sides'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdraft',
            name='ai_assistance_opted_out',
            field=models.BooleanField(default=False),
        ),
    ]
