# Generated by Django 5.2.5 on 2026-08-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0017_ai_assistance_opt_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_assistance_opted_out',
            field=models.BooleanField(default=False),
        ),
    ]
