# Generated by Django 5.2.5 on 2026-09-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0019_filing_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdraft',
            name='notice_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
