# Generated by Django 5.2.5 on 2026-09-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0020_notice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingparty',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
    ]
