# Generated by Django 5.2.5 on 2026-09-07 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("efile", "0022_sync_primary_filing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="filingdraft",
            name="clerk_return",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="filingdraft",
            name="correction_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="filingdraft",
            name="correction_of",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="correction",
                to="efile.filingdraft",
            ),
        ),
        migrations.AddField(
            model_name="filingdraft",
            name="submission_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="filingdraft",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filing_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FilingMetadataEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=40)),
                ("value", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_events",
                        to="efile.filingdraft",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="HandoffDocumentUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="efile.filingdraft",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "idempotency_key"),
                        name="handoff_document_update_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InterviewHandoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=255)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handoff",
                        to="efile.filingdraft",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"), name="handoff_source_identity"
                    ),
                    models.UniqueConstraint(
                        fields=("source", "idempotency_key"), name="handoff_idempotency"
                    ),
                ],
            },
        ),
    ]
