# Generated by Django 5.2.5 on 2026-09-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0023_interview_handoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('jurisdiction', models.CharField(max_length=50)),
                ('registered_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('email', 'jurisdiction'), name='pending_activation_identity')],
            },
        ),
    ]
