# Generated by Django 5.2.5 on 2026-09-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0025_pending_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdraft',
            name='quoted_fee_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
