# Generated by Django 5.2.5 on 2026-09-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0026_filingdraft_quoted_fee_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdraft',
            name='disclaimer_acceptance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
