# Generated by Django 5.2.17 on 2026-09-30 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0027_filingdraft_disclaimer_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentextraction',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='claim_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
