# Generated by Django 5.2.17 on 2026-09-30 17:30

import efile.workflow
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0028_extraction_claim_leases'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdocument',
            name='original_s3_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='filingdocument',
            name='preparation',
            field=models.CharField(blank=True, choices=[('unchanged', 'Original PDF'), ('converted', 'Converted from Word'), ('flattened', 'Form fields locked'), ('converted_flattened', 'Converted and fields locked')], max_length=30),
        ),
        migrations.AddField(
            model_name='filingdocument',
            name='preparation_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filingdraft',
            name='current_step',
            field=models.CharField(choices=[('options', 'Options'), ('filing_path', 'Start'), ('upload_documents', 'Upload documents'), ('preview_documents', 'Preview documents'), ('extraction_review', 'Confirm filing'), ('case_lookup', 'Find your case'), ('case_confirmation', 'Confirm your case'), ('document_checklist', 'Check documents'), ('organize_documents', 'Organize documents'), ('your_information', 'Your information'), ('parties', 'People in this filing'), ('party_details', 'Person details'), ('case_questions', 'Case questions'), ('payment', 'Fees'), ('review', 'Review'), ('confirmation', 'Confirmation')], default=efile.workflow.WorkflowStepKey['OPTIONS'], max_length=64),
        ),
    ]
