# Generated by Django 5.2.17 on 2026-10-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("efile", "0029_document_preparation_and_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="filingdocument",
            name="document_type_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
