# Generated by Django 5.2.17 on 2026-10-02 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0030_document_type_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.CreateModel(
            name='StaffLoginThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('window_started', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='filingdocument',
            name='upload_has_form_fields',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filingdraft',
            name='deletion_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filingdraft',
            name='submission_operation',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='analytics_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('jurisdiction', models.CharField(max_length=40)),
                ('account_wide', models.BooleanField(default=False)),
                ('draft_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('received', 'Received'), ('verified', 'Verified'), ('processing', 'Processing'), ('attention', 'Needs attention'), ('completed', 'Live-system deletion completed')], default='received', max_length=20)),
                ('verified_at', models.DateTimeField(null=True)),
                ('object_keys', models.JSONField(default=list)),
                ('deleted_keys', models.JSONField(default=list)),
                ('counts', models.JSONField(default=dict)),
                ('outcome', models.CharField(blank=True, max_length=40)),
                ('external_cleanup_pending', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_privacy_requests', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(null=True)),
                ('jurisdiction', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=40)),
                ('outcome', models.CharField(max_length=40)),
                ('counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('granularity', models.CharField(default='day', max_length=5)),
                ('jurisdiction', models.CharField(max_length=40)),
                ('metric', models.CharField(max_length=40)),
                ('filing_kind', models.CharField(max_length=10)),
                ('dimension', models.CharField(default='all', max_length=40)),
                ('value', models.CharField(default='all', max_length=80)),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('contributors', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['jurisdiction', 'day'], name='usage_scope_day')],
                'constraints': [models.UniqueConstraint(fields=('day', 'granularity', 'jurisdiction', 'metric', 'filing_kind', 'dimension', 'value'), name='usage_counter_bucket')],
            },
        ),
        migrations.CreateModel(
            name='StaffRoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=40)),
                ('role', models.CharField(choices=[('accounts', 'Account management'), ('analytics', 'Aggregate reporting')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'jurisdiction', 'role'), name='staff_role_scope')],
            },
        ),
        migrations.CreateModel(
            name='StoredUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=1024)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_uploads', to='efile.filingdraft')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('draft', 'key'), name='stored_upload_owner')],
            },
        ),
        migrations.CreateModel(
            name='UsageContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.usagecounter')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'counter'), name='usage_contributor_once')],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=40)),
                ('operation', models.CharField(default='once', max_length=80)),
                ('dimensions', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('counted_at', models.DateTimeField(null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efile.filingdraft')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('draft', 'metric', 'operation'), name='usage_event_once')],
            },
        ),
        migrations.CreateModel(
            name='UsageMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=40)),
                ('identity', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'jurisdiction', 'identity'), name='usage_matter_once')],
            },
        ),
    ]
