# Generated by Django 5.2.17 on 2026-10-03 03:33

import django.db.models.deletion
from django.db import migrations, models


def add_postgres_search_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "CREATE INDEX filing_code_search_gin ON efile_filingcodepath "
            "USING GIN (to_tsvector('simple'::regconfig, COALESCE(search_text, '')))"
        )


def remove_postgres_search_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS filing_code_search_gin")


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0032_inventory_owned_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingCodeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=20, unique=True)),
                ('source_url', models.URLField()),
                ('refreshed_at', models.DateTimeField()),
                ('rules_digest', models.CharField(max_length=64)),
                ('vocabulary', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FilingCodePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.BooleanField()),
                ('court', models.JSONField()),
                ('case_category', models.JSONField()),
                ('case_type', models.JSONField()),
                ('filing_type', models.JSONField()),
                ('search_text', models.TextField()),
                ('filing_terms', models.TextField()),
                ('case_terms', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('explanation_source', models.URLField(blank=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='efile.filingcodeindex')),
            ],
        ),
        migrations.RunPython(add_postgres_search_index, remove_postgres_search_index),
    ]
