# Generated by Django 5.2.17 on 2026-10-06 16:25

import efile.db_expressions
from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class AddCourtIndex(AddIndexConcurrently):
    """Avoid blocking production writes while indexing an existing large catalog."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        else:
            migrations.AddIndex.database_forwards(self, app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == "postgresql":
            super().database_backwards(app_label, schema_editor, from_state, to_state)
        else:
            migrations.AddIndex.database_backwards(self, app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('efile', '0034_sqlite_filing_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingcodeindex',
            name='court_snapshots',
            field=models.JSONField(default=dict),
        ),
        AddCourtIndex(
            model_name='filingcodepath',
            index=models.Index(models.F('index'), efile.db_expressions.CourtCode('court'), name='filing_path_court'),
        ),
    ]
