# Generated by Django 5.2.17 on 2026-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0035_incremental_filing_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent_case_zips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
