# Generated by Django 5.2.17 on 2026-10-07 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0036_user_recent_case_zips'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingCodeCourtCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('revision', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('filing_count', models.PositiveIntegerField(default=0)),
                ('copied_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'code'), name='unique_court_catalog_per_jurisdiction')],
            },
        ),
        migrations.CreateModel(
            name='FilingCodeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('resync', 'Resync codes'), ('rebuild', 'Rebuild code search indexes')], max_length=20)),
                ('jurisdiction', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
