# Generated by Django 5.2.17 on 2026-10-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("efile", "0037_efsp_code_copies_and_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="filingdraft",
            name="existing_case_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="filingparty",
            name="representation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="filingparty",
            name="source",
            field=models.CharField(default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="filingparty",
            name="source_case_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="filingparty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "court"), models.Q(("external_party_id", ""), _negated=True)),
                fields=("draft", "source_case_id", "external_party_id"),
                name="unique_imported_case_party",
            ),
        ),
    ]
