# Generated by Django 5.2.17 on 2026-10-09 21:20

import efile.workflow
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0038_existing_case_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingdraft',
            name='current_step',
            field=models.CharField(choices=[('options', 'Options'), ('filing_path', 'Start'), ('upload_documents', 'Upload documents'), ('extraction_review', 'Confirm filing'), ('case_lookup', 'Find your case'), ('case_confirmation', 'Confirm your case'), ('document_checklist', 'Check documents'), ('organize_documents', 'Organize documents'), ('your_information', 'Your information'), ('parties', 'People in this filing'), ('party_details', 'Person details'), ('case_questions', 'Case questions'), ('payment', 'Fees'), ('review', 'Review'), ('confirmation', 'Confirmation')], default=efile.workflow.WorkflowStepKey['OPTIONS'], max_length=64),
        ),
    ]
