# Generated by Django 5.2.17 on 2026-10-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0039_remove_preview_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdraft',
            name='extraction_review_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
