# Generated by Django 5.2.17 on 2026-10-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0040_extraction_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingdraft',
            name='filing_type_proposal',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
