# Generated by Django 5.2.17 on 2026-10-10 21:00

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models

# Split by stage like the paths' indexes (0042): Illinois' new-case labels
# are 5% of its labels, and a new-case search should not read the rest.
LABEL_SEARCH_INDEXES = (("filing_label_initial_gin", "initial"), ("filing_label_existing_gin", "NOT initial"))


def add_label_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for name, predicate in LABEL_SEARCH_INDEXES:
            schema_editor.execute(
                f"CREATE INDEX {name} ON efile_filingcodelabel "
                f"USING GIN (to_tsvector('simple'::regconfig, COALESCE(search_text, ''))) WHERE {predicate}"
            )


def remove_label_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        for name, _ in LABEL_SEARCH_INDEXES:
            schema_editor.execute(f"DROP INDEX IF EXISTS {name}")


def create_shared_cache(apps, schema_editor):
    call_command("createcachetable", "efile_shared_cache", database=schema_editor.connection.alias, verbosity=0)


def drop_shared_cache(apps, schema_editor):
    schema_editor.execute("DROP TABLE IF EXISTS efile_shared_cache")


class Migration(migrations.Migration):

    dependencies = [
        ('efile', '0042_filing_search_index_by_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filingcodeindex',
            name='labels_built_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FilingCodeLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.BooleanField()),
                ('key', models.CharField(max_length=32)),
                ('filing_type_name', models.TextField()),
                ('case_category_name', models.TextField()),
                ('case_type_name', models.TextField()),
                ('search_text', models.TextField()),
                ('filing_terms', models.TextField()),
                ('case_terms', models.TextField()),
                ('courts', models.JSONField(default=dict)),
                ('index', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='efile.filingcodeindex')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('index', 'key'), name='unique_filing_label_per_index')],
            },
        ),
        migrations.RunPython(add_label_search_indexes, remove_label_search_indexes),
        migrations.RunPython(create_shared_cache, drop_shared_cache),
    ]
