"""Make the copy in state YAML files visible to ``makemessages``.

``xgettext`` reads Python and templates. It does not read YAML, so a sentence a
state wrote in its own config file -- the Vermont About-page partner paragraph,
say -- would never reach the Spanish catalog, and the translated page would drop
back to the default English wording for exactly the strings a partner asked to
change.

This command writes those strings out as a generated Python module full of
``pgettext_lazy`` calls, which ``makemessages`` then picks up like any other
source file. Nothing imports the generated module at runtime; it exists to be
read by ``xgettext``.

    uv run python manage.py extract_config_text
    uv run python manage.py makemessages -l es

Run it whenever a ``text:`` section changes. ``--check`` reports a stale file
without writing one, for CI.
"""

import json

from django.core.management.base import BaseCommand, CommandError

from efile.utils.config_loader import config_loader
from efile.utils.ui_text import UI_STRINGS, config_overrides

GENERATED_PATH = "efile/config_text_strings.py"

HEADER = '''"""Generated by ``manage.py extract_config_text``. Do not edit by hand.

Every user-facing string configured in a state's YAML file, restated as a
``pgettext_lazy`` call so ``makemessages`` can find it. The message context is
the UI text key, matching how ``efile.utils.ui_text`` looks the string up at
request time. Nothing imports this module.
"""

from django.utils.translation import pgettext_lazy

CONFIG_STRINGS = [
'''

FOOTER = "]\n"


def _quote(value):
    """Double-quoted like ruff wants, escaped like Python needs."""
    return json.dumps(value, ensure_ascii=False)


def _render():
    """Return the full text of the generated module."""
    lines = [HEADER]
    for jurisdiction in config_loader.get_available_jurisdictions():
        config = config_loader.load_jurisdiction_config(jurisdiction) or {}
        overrides = {key: value for key, value in config_overrides(config).items() if key in UI_STRINGS}
        if not overrides:
            continue
        lines.append(f"    # {jurisdiction}.yaml\n")
        for key, value in sorted(overrides.items()):
            description = UI_STRINGS[key].description
            if description:
                lines.append(f"    # Translators: {description}\n")
            # Written the way ruff would format it -- double quotes, one argument
            # per line, magic trailing comma -- so a pre-commit run cannot make
            # a freshly generated file look stale to --check.
            lines.append("    pgettext_lazy(\n")
            lines.append(f"        {_quote(key)},\n")
            lines.append(f"        {_quote(value)},\n")
            lines.append("    ),\n")
    lines.append(FOOTER)
    return "".join(lines)


class Command(BaseCommand):
    help = "Write config-authored UI text to a Python stub that makemessages can read."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Exit non-zero if the generated file is missing or out of date, without writing it.",
        )

    def handle(self, *args, **options):
        from django.conf import settings

        path = settings.BASE_DIR / GENERATED_PATH
        generated = _render()
        current = path.read_text() if path.exists() else None

        if options["check"]:
            if current != generated:
                raise CommandError(f"{GENERATED_PATH} is out of date. Run: manage.py extract_config_text")
            self.stdout.write(self.style.SUCCESS(f"{GENERATED_PATH} is up to date."))
            return

        if current == generated:
            self.stdout.write(f"{GENERATED_PATH} is already up to date.")
            return

        path.write_text(generated)
        self.stdout.write(self.style.SUCCESS(f"Wrote {GENERATED_PATH}."))
